-- MySQL Script generated by MySQL Workbench
-- Sun 14 Jun 2020 10:51:29 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`qstprod_producteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`qstprod_producteur` (
  `qstprod_idpkai_producteur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NULL,
  `prenom` VARCHAR(30) NULL,
  `email` VARCHAR(60) NULL,
  `email_bu` VARCHAR(60) NULL,
  `mdpsha` VARCHAR(512) NULL,
  `telfixe` VARCHAR(14) NULL,
  `telport` VARCHAR(14) NULL,
  `nom_ferme` VARCHAR(60) NOT NULL,
  `siret` VARCHAR(14) NOT NULL,
  `adrferme_numvoie` VARCHAR(12) NULL,
  `adrferme_rue` VARCHAR(128) NULL,
  `adrferme_lieudit` VARCHAR(60) NULL,
  `adrferme_commune` VARCHAR(45) NOT NULL,
  `adrferme_cp` VARCHAR(12) NULL,
  `adrferme_compladr` VARCHAR(60) NULL,
  `pageurl_fb` VARCHAR(60) NULL,
  `pageurl_ig` VARCHAR(60) NULL,
  `pageurl_twitter` VARCHAR(60) NULL,
  `url_web` VARCHAR(128) NULL,
  `url_boutique` VARCHAR(128) NULL,
  `orgcertifbio` VARCHAR(30) NULL,
  `typeproduction` VARCHAR(256) NULL,
  `surfacehectterres` DECIMAL(10000,0) NULL,
  `surfacesousserre` DECIMAL(10000,0) NULL,
  `tetes_betail` DECIMAL(10000,0) NULL,
  `hl_par_an` DECIMAL(10000,0) NULL,
  `groupe_cagette` VARCHAR(60) NULL,
  PRIMARY KEY (`qstprod_idpkai_producteur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Données générales du producteur et de sa ferme/exploitation. Adresses ferme.\nDonnées civiles producteur et exploitation agricole. \nDonnées réseaux sociaux. Siret ferme/exploitation.';


-- -----------------------------------------------------
-- Table `mydb`.`cet_sondage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cet_sondage` (
  `cet_sondage_idpkai` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(60) NOT NULL,
  `reponse` VARCHAR(60) NOT NULL,
  `fk_pkprod` INT NULL,
  PRIMARY KEY (`cet_sondage_idpkai`, `fk_pkprod`),
  INDEX `fk_cet_sondage_qstprod_producteur_idx` (`fk_pkprod` ASC),
  CONSTRAINT `fk_pkprod`
    FOREIGN KEY (`fk_pkprod`)
    REFERENCES `mydb`.`qstprod_producteur` (`qstprod_idpkai_producteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Question + reponse à un sondage. Qui répond.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
